import { ShowcaseTabs, TExtendedInitialFormSchema } from '@/ui/Home/ShowcaseTabs/ShowcaseTabs'
import { Button } from '@/ui/__shared__/Button'
import { Spinner } from '@/ui/__shared__/Button/Spinner'
import { ErrorMessage } from '@/ui/__shared__/ErrorMessage'
import { fetcher } from '@/utils/fetcher'
import type { NextPage } from 'next'
import Head from 'next/head'
import useSWR from 'swr'

const tabsKeys = ['form', 'client list', 'data summary']

const Home: NextPage = () => {
  const { data, error } = useSWR<TExtendedInitialFormSchema[]>('/api/users', fetcher)

  return (
    <>
      <Head>
        <title>Mdp Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mx-auto mt-10 sm:mt-20 md:mt-52 px-5">
        <main className="flex flex-col gap-6">
          <header className="flex flex-col gap-1 items-center">
            <h1 className="text-5xl font-extrabold">Welcome!</h1>
            <p className="text-xs text-zinc-400">
              &rarr; Navigate through the tabs to see the details
            </p>
            {!data && <Spinner className="text-indigo-600 mx-auto text-center" />}
          </header>

          <ShowcaseTabs keys={tabsKeys} />

          {error && <ErrorMessage title="Oh, an unexpected error ocurred" />}
        </main>

        <footer className="flex items-center justify-center mt-6">
          Developed by{' '}
          <Button
            designation="link"
            href="https://github.com/AlvaroAquijeDiaz"
            title="alvaro aquije"
            target="_blank"
          />
        </footer>
      </div>
    </>
  )
}

export default Home
